charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/copy-plugins.yaml, charts/sonarqube/templates/install-plugins.yaml, charts/sonarqube/values.yaml, charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/ingress.yaml, charts/sonatype-nexus/templates/proxy-svc.yaml
Merge in the latest changes from helm/charts
=> Community updates for sonarqube and sonatype-nexus

charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/requirements.lock, charts/sonarqube/requirements.yaml, charts/sonarqube/values.yaml
=> Update to sonarqube 8.2

charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/tests/sonarqube-test.yaml, charts/sonarqube/values.yaml
=> Make all images configurable

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/values.yaml, charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml, charts/sonatype-nexus/values.yaml
- charts/sonatype-nexus: Added support for priorityClassName to schedule nexus pod with priority
- charts/sonarqube: Added support for priorityClassName to schedule sonarqube pod with priority
=> Added PriorityClassName to charts/sonatype-nexus, charts/sonarqube

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/ingress.yaml, charts/sonatype-nexus/values.yaml
- sonatype/nexus3 uses an unprivileged user uid: 200, gid: 200 
- ingress syntax fixes
=> fix fsGroup and ingress

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/copy-plugins.yaml
Instead of doing a check on the if, a value is assignment and for that reason the if never is false.
=> fixed bug about keep default sonar plugins.

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/install-plugins.yaml
=> make install_plugins more reliable

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/README.md, charts/sonatype-nexus/values.yaml
=> Update Nexus image

charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/ingress.yaml, charts/sonarqube/values.yaml
=> Remove duplicate paths in ingress

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/_helpers.tpl, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/secret.yaml
Related to already reported issue #131
=> [sonarqube] FIX postgresql password not set for external database

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/README.md, charts/sonatype-nexus/templates/_helpers.tpl, charts/sonatype-nexus/templates/adtl-configmap.yaml, charts/sonatype-nexus/templates/backup-pv.yaml, charts/sonatype-nexus/templates/backup-pvc.yaml, charts/sonatype-nexus/templates/backup-secret.yaml, charts/sonatype-nexus/templates/configmap.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml, charts/sonatype-nexus/templates/ingress.yaml, charts/sonatype-nexus/templates/proxy-ks-secret.yaml, charts/sonatype-nexus/templates/proxy-route.yaml, charts/sonatype-nexus/templates/proxy-svc.yaml, charts/sonatype-nexus/templates/pv.yaml, charts/sonatype-nexus/templates/pvc.yaml, charts/sonatype-nexus/templates/route.yaml, charts/sonatype-nexus/templates/secret.yaml, charts/sonatype-nexus/templates/service.yaml, charts/sonatype-nexus/templates/serviceaccount.yaml, charts/sonatype-nexus/values.yaml
Adding namespace properties to the nexus chart
=> Add namespace to nexus chart

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/service.yaml
Fix namespace property in service yaml
=> bugfix - fix namespace for svc

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/README.md, charts/sonatype-nexus/values.yaml
=> Update Nexus version

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml
see https://github.com/Oteemo/charts/issues/161
=> #161 making ALLOWED_USER_AGENTS_ON_ROOT_REGEX configurable

charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/values.yaml
Expose `schedulerName` so that user can customize it.
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
=> [SonarQube] Add scheduler

.github/workflows/lint-test.yml, .github/workflows/release.yml, charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/backup-pv.yaml, charts/sonatype-nexus/templates/backup-pvc.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml
=> Fix PVC issue

charts/sonarqube/Chart.yaml, charts/sonarqube/values.yaml
Fixed a typo and harmonized extraConfig description.
=> Fixed typo in sonarqube values.yaml

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/install-plugins.yaml, charts/sonarqube/values.yaml
This pull request adds support for `no_proxy` environmental variable.
=> feature: Add no_proxy environmental variable support

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/ingress-docker.yaml, charts/sonatype-nexus/templates/proxy-svc.yaml
=> [nexus] Allow to expose docker registry without enabling the proxy

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/install-plugins.yaml
Added validation before remove elements of the folder.
Add new line for each plugin to install.
=> Bug fixed at install_plugins.sh in sonar-sonarqube-install-plugins configMap

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/NOTES.txt
=> Updated notes.txt

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml
Unfortunately, I made a mistake by excluding the environment variable when the parameter is set to false. Therefore, even with my new implementation it would always be true.
=> Add nexus.chownNexusData parameter (fix)

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/install-plugins.yaml
When noCheckCertificate was true, there was a missing space between flags…
This correct this error.
This really fixes #243
=> Fix missing space for wget call

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/service.yaml
Hey think this is a simple change - sorry if I'm misunderstanding - tested local with GKE and appears to be working fine.  cheers Tony.
=> Allow the ability to pass through a nodePort for the service

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml, charts/sonatype-nexus/values.yaml
Ay,
Related to <https://github.com/Oteemo/charts/issues/186>.
I hope it helps. :)
=> Fix #186 - Adding Java options for Nexus Proxy

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml
This PR provides a way to add labels to nexus pods and pvc.
=> Add labels to nexus pods and pvc

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/backup-pv.yaml, charts/sonatype-nexus/templates/backup-pvc.yaml, charts/sonatype-nexus/templates/backup-secret.yaml, charts/sonatype-nexus/templates/cloudiam-pvc.yaml, charts/sonatype-nexus/templates/pv.yaml, charts/sonatype-nexus/templates/pvc.yaml, charts/sonatype-nexus/templates/serviceaccount.yaml
This PR adds labels to pvs, pvcs, service account and secret
=> Add labels to resources

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml
=> Change env injection order

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml, charts/sonatype-nexus/values.yaml
Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Adds capability to get Envrionment Variables for Configmaps or Secrets.
=> feat(sonatype-nexus): Add envFrom capability for nexus

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/proxy-svc.yaml
Currently service endpoints are not created for the Nexus additionalPorts. This PR purposed to fix it.
=> Nexus svc additionalports

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/deployment-statefulset.yaml, charts/sonatype-nexus/values.yaml
=> Add support for container security context

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/templates/_helpers.tpl, charts/sonatype-nexus/templates/ingress-docker.yaml
Values.ingressDocker.tls.enabled wasn't used in the template. Corrected also a typo in _helpers.tpl
=> Fixed usage of Values.ingressDocker.tls.enabled

charts/sonatype-nexus/Chart.yaml, charts/sonatype-nexus/values.yaml
See Release notes here: https://help.sonatype.com/repomanager3/product-information/release-notes/2021-release-notes
=> Bump nexus to 3.37.3 version

charts/sonarqube/Chart.yaml, charts/sonarqube/values.yaml
Update sonarqube to 8.9.6, bumping chart version 
https://community.sonarsource.com/t/sonarqube-8-9-6-lts-and-9-2-4-released/55359
=> (chore) Update sonarqube to 8.9.6

charts/sonarqube/Chart.yaml, charts/sonarqube/templates/ingress.yaml
Converts $value to string.
Fix #339
=> Fix ingress "wrong type for value" error
