Oteemo/charts

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/_helpers.tpl
Allows to override the `fullname` used in various places. Today, a
helper template function determines the format of the name, and it can't
be overridden. This is inconvenient and unwanted in many cases (e.g.
when tooling maps the app name to a hostname—I want
`sonarqube.example.org`, but today I can only get
`sonarqube-sonarqube.example.org`). It's generally better to allow the
fullname to be explicitly overridden if so desired.
See also: helm/charts#20561.
> [sonarqube] allow overriding app fullname

- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/secret.yaml
- charts/sonarqube/values.yaml
To use already existing secret to connect PostgreSQL you must
define postgresql.existingSecret
Fixes #26
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
> charts/sonarqube: fix incorrect variable postgresqlPasswordSecret

- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/secret.yaml
- charts/sonarqube/values.yaml
To use already existing secret to connect MySQL you must
define mysql.existingSecret
Fixes #31
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
> charts/sonarqube: fix incorrect variable mysqlPasswordSecret

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
charts/sonatype-nexus - Update nexus imageTag to latest
Ref: https://help.sonatype.com/repomanager3/release-notes/2020-release-notes#id-2020ReleaseNotes-RepositoryManager3.21.2
> Update Nexus default imageTag to latest to fix vulnerability

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/templates/route.yaml
- charts/sonatype-nexus/values.yaml
This PR updates the Route and Deployment templates for sonatype-nexus.
*Route*:
- Template needs to have an empty stubbed status object. Otherwise this throws an error (likely due to some openAPI validation that is being done)
*Deployment*:
- When trying to set an empty securityContext (ie `securityContext: []`) a warning is thrown about replacing a table value with a non-table value. Adding the `enabled` field similar to other charts makes this more straightforward to use. I've also defaulted the `enabled` field to true to maintain current functionality.
> nexus: Update route template; Update deployment template

- charts/nexusiq/Chart.yaml
- charts/nexusiq/README.md
Why do we need this change?
----
There is a typo in the instructions related to running helm template. As
someone might run it natively avoid having errors that cause support
requests. Also resolve some issues with extra spaces at the end of several lines
What effects does this change have?
----
* Changes the README.md command for helm template to fix a typo
* General lint fixes related to added spaces at the end of lines
> Typo fix for the nexusiq readme for template

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/ingress.yaml
Howdy, finally located an irritating template bug when using custom rules.
```
failed processing release nexus: helm exited with status 1:
Error: YAML parse error on sonatype-nexus/templates/ingress.yaml: error converting YAML to JSON: yaml: line 22: mapping values are not allowed in this context
Error: plugin "diff" exited with error
```
> fix ingress rules substitution

- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
In https://github.com/Oteemo/charts/blob/f4f684482b7a4f569482635a10851d7b99669a91/charts/sonarqube/templates/copy-plugins.yaml#L13 the deleteDefaultPlugins is used as a boolean as in values.yaml example.
> Fix deleteDefaultPlugins default value

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
The `*.existingClaim` refer to PVC names, not PV.
> Fix doc to clearly spot PVC

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/backup-pvc.yaml
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
Let the user decides if it requires the backup persistent storage regardless
its opinion on backup container feature.
Fixes #68
> Decouple nexusBackup.enabled and nexusBackup.persistence.enabled

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/adtl-configmap.yaml
- charts/sonatype-nexus/values.yaml
This PR adds the ability to include additional ConfigMaps as part of your Nexus deployment. This is particularly useful if you are using Nexus plugins that happen to expect input from ConfigMaps (for example: https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift). Once this is merged, users will then be able to use this chart to use this helm chart for the complete deployment versus being able to include the plugin, but having to configure it seperately from the chart.
Closes #79
> Nexus: Add template to include additional configmaps

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
Adding checksum annotations to force update the deployment if configmap/secrets are changed. 
Currently updating any of the following values does not update the deployment. Changes are only applied after force recreating the pods.
```
plugins:
install:
sonarProperties:
```
[Documentation](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)
> Add default deployment annotations

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/copy-plugins.yaml
the kill signal sent to SQ container is caught by the copy-plugin script and never sent to SQ itself
sending the signal to SQ allows it to terminate gracefully its connections (DB) and processes (CE, ES)
> allow SonarQube to terminate gracefully when its container is killed

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
remove extensions/plugins creation and mounts from the chart to avoid native plugins to be hidden when extra plugins are needed
should fix #61
Maybe I have missed something because I absolutely do not understand why this directory is declared and mount as a volume : the extra plugins were already copied directly in the extensions/plugins by the copy-plugins.sh script from /extensions/plugins/tmp where they are downloaded by the install-plugins.sh script (init container).
This fix has been checked with no extra plugin, some extra plugins, updated native plugins (which was already taken in account by the copy-plugins.sh script by removing old version of native plugin in /extensions/plugins) and with a container crash to check that the extra plugins are stilled copied in the …
> Sonarqube hidden native plugins fix

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/ingress.yaml
This is the new API version for Ingress since k8s 1.15.
Since older version are not maintained anymore we can change this.
Signed-off-by: Guillaume Perrin <guillaume28.perrin@gmail.com>
> Update ingress API version for nexus to networking.k8s.io/v1beta1

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
Some reverse proxies require a backend application to run at a non-root path so multiple backend applications can be differentiated by paths. However, Nexus generates javascript that requests resources at fixed paths causing pages to display 404. The environment variable NEXUS_CONTEXT tells Nexus to run at a non-root path.
The official documentation: https://github.com/sonatype/docker-nexus3
> NEXUS_CONTEXT to run Nexus at a non-root path

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
This is a small behavior when you provide a `caCerts.secret` but this secret does not contain any certificate
> [SONARQUBE] no cacerts handling

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
I am really sorry @rjkernick , I messed up my previous pull request :-(
It did not broke anything but the behavior did not change due to the fact `/tmp/secrets/ca-certs` is not really empty when mounted as a volume.
This new pull request really fixes things.
Tests I performed :
`myvalues.yml` :
```yaml
```
```bash
helm upgrade -i sonarqube . -f myvalues.yml`
```
* SonarQube status : Running
* Certificate check : `keytool -list -keystore /opt/sonarqube/certs/cacerts -storepass changeit | grep fake-le-root` => No result
`certificates.yml` :
```yaml
kind: Secret
apiVersion: v1
metadata:
name: certificates
type: Opaque
data: {}
```
```myvalues.yml
caCerts:
secret: certificates
```
```bash
kubectl apply -f certificates.yml
helm upgrade -i sonarqube . -f myvalues.yml
```
* SonarQube status : …
> [SONARQUBE] no cacerts handling (FIXED)

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/secret.yaml
Hi,
We prefer to use sealed secrets and hence would like the nexus chart to allow using existing secret. This will help us not having to push our secret in unencrypted form to our Git CASC repo.
I have slightly modified the chart so that if you enabled secret but not provided any data then it will expect that the secret already exists
> Add option to use existing secret with sonatype nexus

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/values.yaml
First of all, thanks for creating this chart!
As we ran into some problems with the Webhook functionality, I found out there is a small issue with the way custom CA certificates are handled in the chart. The custom trustStore that is created from caCerts.secret was only passed to the Web JVM of SonarQube, but the Webhooks are called from the Compute Engine JVM.
The variable SONAR_CE_JAVAOPTS can be used to set JVM parameters for the Compute Engine, so I added it to the container env.
Another option would be to add the certs to the default trustStore of the JRE inside the container, just like update-ca-certificates would do it.
This fixes #125
> Sonarqube: pass caCerts also to the Compute Engine JVM

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/tests/test-config.yaml
Sonarqube are restarting because `/sessions/new` is not the endpoint to be checked Sonarqube healthy.
https://community.sonarsource.com/t/using-the-health-check-api/16325
> Fix Sonarqube health check

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/_helpers.tpl
- charts/sonatype-nexus/templates/ingress-docker.yaml
- charts/sonatype-nexus/values.yaml
to provide configuration flexibility. Closes #96.
The split of ingress into http ingress and docker registry ingress is required to gain extra flexibility and allow separate configuration of ingresses. The configuration below allows to have extra hostnames for nexus http ingress and docker registry ingress.
```yaml
nexusProxy:
env:
nexusHttpHost: nexus.example.com
nexusDockerHost: docker.example.com
ingress:
enabled: true
annotations:
nginx.ingress.kubernetes.io/upstream-vhost: nexus.example.com
rules:
- host: nexus-extra.example.com
http:
paths:
- backend:
serviceName: nexus-sonatype-nexus
servicePort: 8080
path: /
ingressDocker:
enabled: true
annotations:
nginx.ingress.kubernetes.io/upstream-vhost: docker.example.com
rules:
- host: docker-extra.example.com
http:
paths:
- backend: …
```
> split ingress into http ingress and docker ingress 

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/backup-secret.yaml
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
This PR enables the following variables of Nexus-Backup to receive custom values:
- `GRACE_PERIOD`
- `OFFLINE_REPOS`
- `NEXUS_AUTHORIZATION`
Although `NEXUS_AUTHORIZATION` is already set by the secret created with the value of `nexusBackup.nexusAdminPassword`, being able to set its value directly on a environment variable enables the use of secret manager such as HashiCorp Vault.
> [charts/sonartype-nexus] includes env values of nexusBackup

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/clusterrolebinding.yaml
- charts/sonatype-nexus/values.yaml
ClusterRoleBinding is needed when some ClusterRole must be assigned to Pod's ServiceAccount in order to some integration works. For example, [vault mutating webhook](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/) requires it.
> [charts/sonatype-nexus] feat: adds ClusterRoleBinding

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/_helpers.tpl
- charts/sonatype-nexus/values.yaml
Closes #93 
As mentioned in that issue, having the version number in the labels for all the resources is problematic for StatefulSets and PVCs. This removes that version number and just uses the chart name instead which shouldn't change in future. Obviously this will cause one last breakage for affected users but future upgrades should be less painful.
Here is an example error I encountered when going from 3.1.1 to 3.2.0 of the Helm chart:
`cannot patch "sonatype-nexus" with kind StatefulSet: StatefulSet.apps "sonatype-nexus" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`
The fix was to delete the StatefulSet and redeploy which isn't ideal.
In addition I've increased the default …
> [sonatype-nexus] Fix statefulset label issues

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/install-plugins.yaml
Plugins download directory should be purged before downloading to avoid existing file error.
> Sonarqube: fix plugins download

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/cloudiam-pv.yaml
- charts/sonatype-nexus/templates/cloudiam-pvc.yaml
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
- pom.xml
Since travelaudience's Nexus-Backup container just needs a service account key file to be provided to it, this pull request sets up a PV/PVC called "/nexus-data/cloudiam", and sets up the $CLOUD_IAM_SERVICE_ACCOUNT_KEY_PATH to point to a file "service-account-key.json" in that directory.
> Configure GCP backup without deploying nexus itself to Google Cloud

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
README has default as ClusterIP but default in file is NodePort.  Update README to match default.
> Matche README to file

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
> postgres condition applied to wait-for-db initContainer

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
Add affinity labels in values.yaml and deployment-statefulset.yaml allow the use of this K8s feature.
Node affinity allows you to constrain which nodes your pod is eligible to be scheduled on, based on labels on the node.
> Add affinity labels allow the use of this K8s feature.

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
I introduced a new parameter called nexus.chownNexusData.
When the docker-nexus container starts it executes the following file /etc/service/nexus/run which does the following:
```
#!/bin/sh
if [ "$NEXUS_DATA_CHOWN" == "true" ]; then
chown -R nexus:nexus /opt/sonatype
chown -R nexus:nexus /nexus-data
fi
```
As you can see when the environment variable NEXUS_DATA_CHOWN is set (Default: true, https://github.com/travelaudience/docker-nexus/blob/5c386f3e2154decbf5e521714fc9b8f204b873a4/Dockerfile#L23) . 
The owner for the full /opt/sonatype and /nexus-data directory is set. This behaviour is fine as long as the amount of artifacts is not too large. Unfortunately, in our case we have quite a large amount of artifacts which would lead to startup times of close to 45 minutes but before that the …
> Add nexus.chownNexusData parameter

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
This PR adds support for arbitrary ports setup on the deployment/statefulset.
This is useful in cases like the one described at https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images where it's required to use more ports than the one available by setting the value `nexus.dockerPort`.
Solves #132
> arbitrary ports to deployment-statefulsets

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
Restore plugin directory mount behaviour as in v9.2.6 and before, in case of no persistence enabled.
> sonarqube: fix #250

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/ingress.yaml
if you use GCP as a cloud provider you need to set a default backend to avoid useless default backend created by the gce controller. To add this default backend you must set "ingress.class" annotation with "gce" or "gce-internal" value. 
I haven't managed Kubernetes or AWS workaround because I don't know if it is needed (and i'm not aware about those platform)
Let me know if my statements will work as is.
> Add a default backend for GCE ingress controller

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/change-admin-password-hook.yml
- charts/sonarqube/values.yaml
Hi!
I would like to add support for adding annotations to the admin hook job, since there are container injection services like Istio, whose way to enable / disable them is through annotations.
Regards!
> Add support for setting custom annotations in admin hook job

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/change-admin-password-hook.yml
Fixes GH-277 by using the `urlquery` helm function with the current/net admin password in the change-admin-password-hook job
> GH-277, URL escape admin passwords in change-admin-password-hook job

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
Actually the `initContainer.securityContext` value set all the securityContext for all containers except the 'wait-for-db' one.
This PR simply set the securityContext to the 'wait-for-db' initContainer the same way than the other initContainers.
It may be considered as a breaking change as it can break the wait-for-db initContainer depending on what people specified in the `initContainer.securityContext` already.  
If you prefer, I can also add a new value in `values.yaml` file to set the wait-for-db securityContext (something like `waitForDb.securityContext`). 
IMO normalization is always better. But the decision is yours.
> Add securityContext to wait-for-db initContainer like the other initContainers

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/ingress.yaml
- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/ingress-docker.yaml
- charts/sonatype-nexus/templates/ingress.yaml
> Fix ingress api checks

- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
Updates to the latest 8.x community image to mitigate CVE-2021-45046 and CVE-2021-44228 as detailed here: https://community.sonarsource.com/t/sonarqube-sonarcloud-and-the-log4j-vulnerability/54721
Required a DB migration, but everything went without issue as it usually does :)
> chore(sonarqube): update image tag to 8.9.5-community

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/ingress.yaml
A previous PR #330  - broke the expected behaviour when applying the chart with only the host and path values set meaning that people now have to set `pathType: Prefix` in all of their values. Setting the value to default to "Prefix" will allow users to avoid the sudden unexpected (and breaking) config change, maintaining the previous behaviour.
> fix(Ingress/pathType): default to Prefix

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/deployment-statefulset.yaml
- charts/sonatype-nexus/values.yaml
Add a `startupProbe` for nexus.
Nexus can take a lot of time to start, especially when big volumes are mounted, so we can add a startup probe to avoid long delay on `liveness` and `readiness` probe in case of a restart.
> Add startup probe for sonatype-nexus

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
Simply bumping up to the newest version of sonatype-nexus as 3.38.x fixes an HTML injection attack and enables a Log4JVisualizer chart.
> Bumping sonatype-nexus version
